### PR TITLE
change read_pos and read_ino. relate #1953 #1804

### PR DESCRIPTION
**Pull request by jl2005**
Signed-off-by: 焦龙 <jiaolongdy@163.com>

### CODE REVIEW

**Comment by repeatedly** [comment]
Travis-CI failed. This patch is something wrong.

**Comment by jl2005** [comment]
@repeatedly Travis-CI failed is due to some known problems. Not caused by this change.

https://github.com/fluent/fluentd/issues/1434

**Comment by repeatedly** [comment]
I re-run tests several times and all tests always failed.
So #1434 is different issue.

**Comment by jl2005** [comment]
@repeatedly I fixed Travis-CI error. Can you merge it?

**Comment by repeatedly** [comment]
@kazegusuri How about this approach?

**Comment by kazegusuri** [comment]
Oh.. sorry, I haven't noticed your mention. I will check it later.

**Comment by kazegusuri** [comment]
LGTM! This will fix the issue to access read_pos and read_inode from another thread.

**Comment by repeatedly** [comment]
Merged. Thanks for the patch!

**Pull request merged**
