### PR TITLE
Close files explicitly in in_tail

### PR DESCRIPTION
**Pull request by tagomoris**
File handles are not closed explicitly now, and it makes troubles on Windows (especially in tests).
After detaching watchers (and stops all threads including event loop), no threads touches to IO objects and file handlers.
File handles should be closed after that.

### CODE REVIEW

**Comment by tagomoris** [comment]
I'm seriously confused about why #1312 fails on Windows CI only with ruby 2.1 and 2.2, but root cause of that problem is not to close files in IOHandler.
This change fixes that problem.

**Comment by tagomoris** [comment]
@repeatedly could you check this?

**Comment by repeatedly** [comment]
Will check :)

**Comment by tagomoris** [comment]
@repeatedly ping

**Comment by repeatedly** [comment]
LGTM

**Comment by tagomoris** [comment]
Failing CI task is fixed at #1331.

**Pull request merged**
