### PR TITLE
[#649] record_transformer support remove keys structured data

### PR DESCRIPTION
**Pull request by llby**
record_transformer's `remove_keys` only support remove first hierarchy keys of record.
`remove_json_keys` remove structured data of record['message']. When It is json.
from issue #649

If it work fine. Then I'll try to #902.

### CODE REVIEW

**Comment by tagomoris** [comment]
@llby Could you add what you want in description?

**Comment by tagomoris** [comment]
For nested key-values, we don't have any common syntax to specify it in records.
I think we can't accept this change because this change uses JSON in unique way, and it can't be used for other plugins.

For nested key-values, we already have an item to make plugin helpers to handle it. But we need many discussions about what syntax/API is the best for it before implementing it.
https://github.com/fluent/fluentd/wiki/Changes-proposed-for-v0.14.x#misc-development-tasks

**Comment by llby** [comment]
Hmm..
That's right.
I understand.

**Comment by okkez** [comment]
#1800 resolves this PR.
Could you close this PR? @repeatedly

**Comment by repeatedly** [comment]
Ah, I forgot to close this. Thanks for the notification.

**Pull request closed without merging**
