### PR TITLE
add Fluent::Plugin::BareOutput to support v0.12 MultiOutput plugins

### PR DESCRIPTION
**Pull request by tagomoris**

### CODE REVIEW

**Comment by tagomoris** [comment]
@sonots Please check this change

**Comment by sonots** [comment]
For the problem of ERROR2 of https://github.com/fluent/fluentd/issues/973, I got another error for config-expander as

```
Error: test_emit(ConfigExpanderOutputTest): RuntimeError: BUG: use router.emit instead of Engine.emit
```

I also have one question: what does "bare" infer? How plugin developers choose a parent class, `Output` or `BareOutput` to create an output plugin?

**Comment by tagomoris** [comment]
It's intentional to prohibit `Engine.emit`... it will not be fixed so far.
`BareOutput` is very limited and skinny one, and it's not for almost plugin authors. it's just for meta plugins like forest, config-expander or something like that.

**Comment by sonots** [comment]
Okay, so compatibility layer for `Engine.emit` is not provided. 
I understand that we have to tell about it to plugin developers. 

Code itself looks good to me.

**Comment by tagomoris** [comment]
Once I thought about `Engine.emit`, but that is just under `Fluent::`, and no space to override for compatibilities. And that change is of v0.12 originally (we should have shown "deprecated" message in v0.12 versions).

**Comment by tagomoris** [comment]
I added some comment to tell not to use this for normal output plugins.

**Pull request merged**
