### PR TITLE
Add v1.13.0 changelog entries

### PR DESCRIPTION
**Pull request by kenhys**
**Which issue(s) this PR fixes**: 

Fixes N/A

**What this PR does / why we need it**: 

This is PR for preparing v1.13.0 changelog entries.

**Docs Changes**:

v1.13.0 blog entry is also making progress here:

https://github.com/fluent/fluentd-website/pull/146

**Release Note**: 

N/A

### CODE REVIEW

**Comment by kenhys** [comment]
Added https://github.com/fluent/fluentd/pull/3380

**Comment by kenhys** [comment]
rebased with master (merge v1.12.4)

**Review by ashie — CHANGES_REQUESTED** [review]
Could you follow the commit format like this?: https://github.com/fluent/fluentd/commit/b6e76c09d60ee866de6470f2bdd2551e7c8591d3

* Commit message should be `v1.13.0`
* Increment version number in lib/fluent/version.rb

**Comment by kenhys** [comment]
@ashie  I'll do it, thanks.

**Comment by kenhys** [comment]
Fixed.

**Review by ashie — APPROVED** [review]

**Pull request merged**
