### PR TITLE
Add data_counter in buf_file.rb and buf_memory.rb to count the number…

### PR DESCRIPTION
**Pull request by LarryLo**
In my production scenario, I need to count the number of events in a chunk. 
Is there any function including this mechanism?

### CODE REVIEW

**Comment by cosmo0920** [comment]
Could you write test code?

> In my production scenario, I need to count the number of events in a chunk. 

For example, [fluent-plugin-numeric-counter](https://github.com/tagomoris/fluent-plugin-numeric-counter) or [metricsense](https://github.com/treasure-data/fluent-plugin-metricsense) are not suitable your production scenario?

**Comment by repeatedly** [comment]
flowcounter or flowcounter_simple plugin seems enough for this purpose.

**Comment by LarryLo** [comment]
Thanks for your reply.

I will check it immediately.

Best regards,

羅如宏 R.H.Lo, Larry Lo
*larry.lo1025@gmail.com* <larry.lo1025@gmail.com>
*0921207338*

2016-01-25 16:14 GMT+08:00 Masahiro Nakagawa <notifications@github.com>:

**Comment by LarryLo** [comment]
Sorry to disturb you again.

In my scenario, I have to know the count of events in a buffer chunk while
flushing.

fluent-plugin-numeric-counter
<https://github.com/tagomoris/fluent-plugin-numeric-counter> and flowcounter
are all good plugins but not really fit my purpose.

Best regards,

羅如宏 R.H.Lo, Larry Lo
*larry.lo1025@gmail.com* <larry.lo1025@gmail.com>
*0921207338*

2016-01-25 16:18 GMT+08:00 羅如宏 <larry.lo1025@gmail.com>:

**Comment by repeatedly** [comment]
https://github.com/tagomoris/fluent-plugin-buffer-lightening has this feature

**Comment by LarryLo** [comment]
Great! 
I've seen the source code and it looks perfect.
I will close this PR immediately.

**Pull request closed without merging**
