### PR TITLE
Add rfc5424 regex without priority 

### PR DESCRIPTION
**Pull request by cosmo0920**

### CODE REVIEW

**Comment by mururu** [comment]
Should we also fix `REGEXP_DETECT_RFC5424`?

**Comment by cosmo0920** [comment]
I have no idea for now. 
In without priority case, should we detect with `time_format` and @rfc5424_time_format?

**Comment by repeatedly** [comment]
I don't think so. `REGEXP_DETECT_RFC5424` is mainly used for in_syslog and there is no use case for syslog based file log.

**Comment by mururu** [comment]
I see.

**Comment by repeatedly** [comment]
Thanks!
@cosmo0920 Could you send same patch to v0.12 branch?

**Comment by cosmo0920** [comment]
Sure. I'll do it.  :)

**Pull request merged**
