### PR TITLE
backport: Add test for log related class and module

### PR DESCRIPTION
**Pull request by okkez**
* `Fluent::Log`
* `Fluent::PluginLogger`
* `Fluent::PluginLoggerMixin`

See #909

### CODE REVIEW

**Comment by tagomoris** [comment]
I have no idea why AppVeyor doesn't execute builds...

**Comment by okkez** [comment]
Please check https://ci.appveyor.com/project/fluent/fluentd/settings
Does build against master branch only?

**Comment by okkez** [comment]
BTW, v0.12 doesn't support Windows yet?

**Comment by cosmo0920** [comment]
It's weird...v0.12 branch is specified in appveyor.yml: https://github.com/fluent/fluentd/blob/master/appveyor.yml#L16-L21

Ah, I got it. v0.12 branch does not have `appveyor.yml`.

**Comment by cosmo0920** [comment]
> BTW, v0.12 doesn't support Windows yet?

Yep, Windows support is one of the special feature on v0.14.

**Pull request merged**
