### PR TITLE
Make the worker lock work in '--daemon' mode as well

### PR DESCRIPTION
**Pull request by fujimotos**
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>

**Which issue(s) this PR fixes**: 
Fixes https://github.com/fluent/fluent-package-builder/issues/411

**What this PR does / why we need it**: 

75ef92f introduced automatic clean up as follows:

    Dir.mktmpdir("fluentd-lock-") do |lock_dir|
        ENV['FLUENTD_LOCK_DIR'] = lock_dir
        se.run
    end

This does not work with `--daemon`, because `se.run` will not
block with that option. Fix this issue by reverting to the manual
clean up method in the initial version.

**Docs Changes**:

N/A

**Release Note**: 

`out_file: Fix append mode with --daemon flag.`

### CODE REVIEW

**Review by ashie — APPROVED** [review]
LGTM

**Comment by fujimotos** [comment]
NOTE: I test this patch more (probably for some hours) and will merge this myself.

**Comment by daipom** [comment]
Thanks for the fix!
I'm sorry for overlooking that `se.run` doesn't block with this option.

**Comment by fujimotos** [comment]
OK. I can confirm that this patch works both on Linux and Windows.

In particular, I built a custom td-agent package that contains this patch
and confirmed the package on both platforms (RHEL and Windows).

So I believe this is releasable now.

**Pull request merged**
