### PR TITLE
Added keep_time_key option to parsers

### PR DESCRIPTION
**Pull request by sonots**
This patch allows to use `keep_time_key` option in `in_tail` plugin. 

Now, writing config like:

```apache
<source>
  type tail
  path /var/log/nginx/access.log
  pos_file tmp/access.log.pos
  tag accesslog
  format /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<remoteuser>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<forwardedfor>[^"]*)")?$/
  time_format %d/%b/%Y:%H:%M:%S %z
  keep_time_key true
</source>
```

keeps the `time` field in records.

### CODE REVIEW

**Comment by sonots** [comment]
I am wondering that whether I should add the `time` field with `to_i`ed value or the original string value.
Currently, the original string is the default, and we can specify `include_time_key integer` to get `to_i` value. 

Any opinions?

**Comment by kenjiskywalker** [comment]
Great pull request! Thanks sonots-san!

> Currently, the original string is the default, and we can specify include_time_key integer to get to_i value.

:+1: 

If  added option I going to use string(default).

**Comment by sonots** [comment]
Decided

1. Change the option name `include_time_key` to `keep_time_key` avoid possible option name conflictions.
2. Drop the `integer` option. Now, `keep_time_key` is a bool option.

Changed the PR title.

**Comment by sonots** [comment]
Added `time_key` option for RegexpParser to change the record key name.

**Comment by repeatedly** [comment]
I still don't know time_key option in RegexpParser is useful or not
If someone wants to set time to any filed, record_transformer does.

In my fluentd experience, I didn't receive time_key like feature request.
So I can't imagine the useful situation.

**Comment by sonots** [comment]
If we add keep_time_key, users may feel as they want to change the name of the time field. In such situation time_key option is useful.

I think keep_time_key is useful because I often am asked how to add time field in records. This option enables to do it without using any filter plugins.

I am rather thinking as the behavior of keep_time_key true can be a default, but to keep lower version compatibility, I am setting it as default false.

**Comment by sonots** [comment]
Some lists of users' voides (I will add if I find more):

* http://qiita.com/rch850/items/3b7ce04e38c85a1ce5d0
* https://twitter.com/fujiwara/status/592602918756294656
* https://github.com/fluent/fluentd/pull/587#issuecomment-97014238

**Comment by repeatedly** [comment]
I agree keep_time_key is useful but I don't agree time_key option is useful.

**Comment by sonots** [comment]
Why? LTSVParser or other parsers has it. Only RegexpParser does not have it.

**Comment by repeatedly** [comment]
Because RegexpParser can specify `(?<time>)` for log time but
other formats are not. LTSV, JSON and others are already parsed.

**Comment by sonots** [comment]
I have to store the JSON key name as `logtime` to insert into my company's hadoop. This is my company's tradition. 

Using `keep_time_key and `(?<time>)`, the record key becomes `time` and it does not fit with the use case.

**Comment by repeatedly** [comment]
It seems to be resolved by record_transformer filter.
Hmm... does someone want to use this feature?
If some users want, I will re-consider it.

**Comment by sonots** [comment]
As you know, keep_time_key itself can be resolved with record-transformer.

The aim of this PR is to achieve the goal without using record-transformer or othe filters by providing a simple interface for users, especially beginners.

**Comment by sonots** [comment]
Without time_key option for RegexpParser, some users including me still have to use record-transformer, I want to avoid such inconvenience.

**Comment by repeatedly** [comment]
> As you know, keep_time_key itself can be resolved with record-transformer.

Yes but first parser behaviour is time key is included.
I'm not sure why time key is removed.
I think first behaviour is better so I agree keep_time_key is useful.

**Comment by repeatedly** [comment]
BTW, including two features in one PR is wrong way.

**Comment by sonots** [comment]
time_key for RegexpParser without keep_time_key is useless as you said. So, I moved it to this as I wrote.

**Comment by sonots** [comment]
The aim of this PR is not to use record-transformer to add time field is records, so they should be considered together.

**Comment by sonots** [comment]
By the way, can `keep_time_key true` be default by any chance? We may be able to remove this option itself in the future.

**Comment by sonots** [comment]
https://groups.google.com/forum/#!topic/fluentd/U85Qjll2Y-o

This guy wants to treat `time` field as a normal field. To achieve this, `time_key foo` for RegexpParser is more suitable than `keep_time_key` option. Adding `time_key` option for RegexpParser should go.

**Comment by repeatedly** [comment]
> To achieve this, time_key foo for RegexpParser is more suitable than keep_time_key option.

In his case, keep_time_key is enough because he says "How to keep the 'time' field of fluentd message" in thread title. He doesn't seem to want to change time key.

**Comment by repeatedly** [comment]
> By the way, can keep_time_key true be default by any chance?

v1 or v2. Maybe, v1 is better.

**Comment by sonots** [comment]
He is saying as

> I don't want it to be consider as time, I want to treat it as normal field

So, it looks he wants to skip `TIme.parse` itself. `keep_time_key` does not to allow to skip `Time.parse`. 

BTW, I remembered that I had conf files configuring as `(?<vtime>)` to skip `Time.parse`, and then rename to `time` for performance issue.

**Comment by repeatedly** [comment]
> So, it looks he wants to skip TIme.parse itself.

We can think this because we know fluentd's internal deeply. But in user side, user doesn't know such action in general.
Parsing time is needed for fluentd event so it is no problem. His problem seems parsed time is removed from the record. So the best is keeping time with original string like `{"msg":"log message", "time":"May 4, 2015..."}`.

Skip parsing time causes time gap between log generated time and log collected time. Using log collected time is unexpected behaviour for almost users.

**Comment by sonots** [comment]
summary: time_key has two effects:

1. to chang key field name on keep_time_key true
2. skip Time.parse itself

I think this option is worth to add.

**Comment by sonots** [comment]
Reopened https://github.com/fluent/fluentd/pull/588, and moved the `time_key` option patch from here.

**Comment by repeatedly** [comment]
Okay. Let's merge.

**Pull request merged**
