### PR TITLE
Allow escaping "," in paths for tail input

### PR DESCRIPTION
**Pull request by herrsebi**
Currently there is no way to tail files that include a comma (,) in their file name. Switching to a neg-lookbehind regex should enable this.

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you show me the path example?

**Comment by herrsebi** [comment]
Sure: `/tmp/test,dev.log` would be a vaild file name on unix system. In windows environments, a long filename (longer than 8 chars) may also contain a comma.

**Comment by repeatedly** [comment]
Hmm... support special case is not good for me.
How about using dummy's message like approach?

https://github.com/fluent/fluentd/blob/ced6387cd8f00feede48de2ceb005d72f9a477e9/lib/fluent/plugin/in_dummy.rb#L42

For ',' or other special case, use `path ["p,ath1", "path2"]`.
This approach keeps to support `path path1,path2` string parameter with `split(',')`.

**Comment by herrsebi** [comment]
I've added an alternative 'paths' config setting, that would allow the form of configuration that you mentioned previously.
So now it's either 
` path: "test.log, test2.log"`
or
` paths: ["test.log", "test2.log"]`

The latter form can then also include commas.

**Comment by mkoerperriag** [comment]
Can I help somehow to get this further?

**Pull request closed without merging**
