### PR TITLE
Fix MessagePackEventStream issue with Enumerable methods

### LINKED ISSUE #2099: MessagePackEventStream returns only first event
After calling `any?` or `first()` on an instance of MessagePackEventStream which contains multiple events,  iterating over it using `each` returns only the first event and the stream `size` is 0.

Here is a minimal reproduction:
```
require 'fluent/event'

time = Fluent::EventTime.now
array_stream = Fluent::ArrayEventStream.new([[time, {'a' => 1}], [time, {'a' => 2}]])
mp_stream = Fluent::MessagePackEventStream.new(array_stream.to_msgpack_stream)

puts mp_stream.any?

puts mp_stream.size # Prints 0

mp_stream.each do |time|
  puts time # Executes only once
end
```

Commenting the call to `any?` makes it work as it should. Am I missing something here?
I noticed it trying to debug a specific filter directly following a forward-input. 
I'm using fluentd 1.2.4.

### PR DESCRIPTION
**Pull request by osela**
Fixes #2099

### CODE REVIEW

**Comment by ashie** [comment]
Your claim seems reasonable, the current code breaks the behavior of `each` method.
I've rebased it to resolve a conflict.

**Comment by ashie** [comment]
I'm not sure it's caused by this PR but a test always fails only on macOS:

```
2021-03-18T01:13:23.2565690Z Failure: test_truncate_file(TailInputTest)
2021-03-18T01:13:23.2578720Z /Users/runner/work/fluentd/fluentd/test/plugin/test_in_tail.rb:606:in `test_truncate_file'
2021-03-18T01:13:23.2579850Z      603:     end
2021-03-18T01:13:23.2580550Z      604: 
2021-03-18T01:13:23.2581250Z      605:     events = d.events
2021-03-18T01:13:23.2582050Z   => 606:     assert_equal(3, events.length)
2021-03-18T01:13:23.2582940Z      607:     assert_equal({"message" => "test3"}, events[0][2])
2021-03-18T01:13:23.2583830Z      608:     assert_equal({"message" => "test4"}, events[1][2])
2021-03-18T01:13:23.2584750Z      609:     assert_equal({"message" => "test1"}, events[2][2])
2021-03-18T01:13:23.2585550Z <3> expected but was
2021-03-18T01:13:23.2586080Z <1>
```

It doesn't seem occur on master branch.

**Comment by ashie** [comment]
I've finally got succeeded result at about 10th challenge.

**Comment by ashie** [comment]
I've finally got succeeded result at about 10th try:

https://github.com/fluent/fluentd/pull/2116/checks?check_run_id=2136159348

I think this PR doesn't root cause of it, It may make it easy to reproduce this problem though.

**Review by ashie — APPROVED** [review]

**Review by cosmo0920 — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
