### PR TITLE
Add ParserTestDriver

### PR DESCRIPTION
**Pull request by cosmo0920**
Currently, fluentd does not have `ParserTestDriver`.
This PR adds this test driver.

### Remaining tasks

- [x] Frozen ParserTestDriver API
  - [x] ~~Decide whether to include utility methods such as `str2time` or not.~~
- [x] Replace a few parser test cases with `ParserTestDriver`
- [ ] Documentations?

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you replace one actual parser test using this driver?

**Comment by cosmo0920** [comment]
I try to replace `TimeParser` and `SyslogParse` test cases with `ParserTestDriver`.

**Comment by cosmo0920** [comment]
I've found that parser test driver in this commit https://github.com/cosmo0920/fluentd/commit/d5d0846e8af444cbddbb3e3a03e6df19b7875ef0 does not handle to instantiate `RegexParser`.
How do we abstract this parser with this test driver?

**Comment by okkez** [comment]
I want to write parser test like following:

```ruby
def test_multiline
  conf = %[
  <grok>
    pattern %{DATA:message1}\n
  </grok>
  <grok>
    pattern %{DATA:message2}\n
  </grok>
  ]
  text = <<TEXT
host1 message1
  message2
TEXT
  d = Fluent::Parser::TestDriver.new(Fluent::TextParser::MultilineGrokParser).configure(conf)
  d.parse(text) do |time, record|
     assert_equal(expected, record)
  end
end
```

This is same as other test drivers.

**Comment by repeatedly** [comment]
TimeParser itself is not a Parser plugin so I think supporting TimeParser API is not needed.

**Comment by cosmo0920** [comment]
Rebased. I removed a commit which replaces TimeParse test cases with ParserTestDriver.

**Comment by repeatedly** [comment]
@okkez How about this? If you ok, I will merge this patch.

**Comment by okkez** [comment]
How to use nested config_section and cnofig_param?
How about this?

But this is no tested.

```ruby
def configure(conf)
  case conf
  when Fluent::Config::Element
    @config = conf
  when String
    io = StringIO.new(conf)
    @config = Cofig::Parser.parse(io, 'fluent.conf')
  when Hash
    @config = Config::Element.new('ROOT', '', conf, [])
  else
    raise "Unknown type... #{conf}"
  end
  @instance.configure(@config)
  self
end
```

**Comment by cosmo0920** [comment]
As a result of @okkez and I discussion, I added commits to drop `TimeParser` support in this test driver, fix usage of `Class.new`, and string literal support in `#configure`.

Could you review this PR again?

**Comment by repeatedly** [comment]
If there are no concerns from other developers, I will merge it.

**Comment by okkez** [comment]
Looks good to me :+1:

**Pull request merged**
