### PR TITLE
Perfect documentation

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

**Which issue(s) this PR fixes**: 
NONE

**What this PR does / why we need it**: 
Perfect documentation.
**Docs Changes**:

**Release Note**:

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
Why can't I pass the machine test?

**Comment by repeatedly** [comment]
Thanks!

> Why can't I pass the machine test?

Because fluentd uses multiple threads heavily and travis machine is sometimes too unstable, slow performance/io.

**Pull request merged**
