### PR TITLE
Use separate search prefix for gems and additional plugin path

### PR DESCRIPTION
**Pull request by HatsuneMiku3939**
Allow to search plugin from multiple prefix directory. 

Related with issue #1131 (v0.14 doesn't load plugins from directory specified by "-p" option)

### CODE REVIEW

**Comment by tagomoris** [comment]
With this change, Fluentd seems to load all `in_*.rb` files from anywhere possible. Is it correct and intentional?
Fluentd should load plugins from directory specified by `-p DIR` (primal), or gems which have paths like `fluent/plugin/in_*.rb`.

**Comment by HatsuneMiku3939** [comment]
No. It's not intentional. Thanks for mention it.

It seems to we need two rule of plugin search prefix. 
* for specified directory (not have paths like `fluent/plugin/in_*.rb`)
* for gems

**Comment by HatsuneMiku3939** [comment]
This is working as we expect. but not looks good to me. 
Do you have an idea to improve this?

**Comment by tagomoris** [comment]
Current your implementation is breaking code compatibility of `Registry` class. It might be used by any 3rd party plugins. It can't be merged.

**Comment by tagomoris** [comment]
My idea is to add optional keyword argument (like `file_prefix` or some better name) to be used only for `@paths`, earlier than `@search_prefix`.

**Comment by HatsuneMiku3939** [comment]
@tagomoris 
Sorry for breaking change. actually, I didn't realize `Registry` is opened to 3rd party plugins. Thanks for mention it.

How about this one? https://github.com/HatsuneMiku3939/fluentd/commit/d57576af199b3171d190263caa67ef3a3c9c821d

**Comment by tagomoris** [comment]
@HatsuneMiku3939 it looks good to me!

**Comment by HatsuneMiku3939** [comment]
@tagomoris 
Thanks!

**Comment by repeatedly** [comment]
LGTM

**Pull request merged**
