### PR TITLE
Migrate out_file to v0.14 API

### PR DESCRIPTION
**Pull request by okkez**
TODO

* [x] Add test using sub sections (parse, inject, buffer)

### CODE REVIEW

**Comment by repeatedly** [comment]
Any progress on this patch?

**Comment by tagomoris** [comment]
I'm writing an internal feature for parser/formatter/others to provide TimeParser/TimeFormatter & timezone configurations.
This change will be updated after that code.

**Comment by tagomoris** [comment]
I added the feature to handle TimeParser/TimeFormatter in parser/formatter plugins & inject/extract plugin helpers.
@okkez Could you update this patch on those?

**Comment by okkez** [comment]
OK, I will work for this after RubyKaigi2016.
Maybe 9/13 or later :bow:

**Comment by okkez** [comment]
@tagomoris I've pushed changes use new TimeFormatter.
Could you check latest 3 commits?

**Comment by tagomoris** [comment]
`@formatter.time_formatter_create` in output plugin code looks bad :P 
I suppose we need parameters for plugins to control timezones...

**Comment by tagomoris** [comment]
Mmm. I'll take this task, because there are some difficult points to be considered...

**Comment by tagomoris** [comment]
I re-created the change as #1257. Thank you to show me problems and basic form to be done.

**Pull request closed without merging**
