### PR TITLE
use params when body is empty

### PR DESCRIPTION
**Pull request by wd**
As discussed at https://groups.google.com/forum/#!topic/fluentd/GCfGSP-rBpA, I simply create this PR. I don't master ruby and fluentd well, maybe someone can give a better solution :)

### CODE REVIEW

**Comment by repeatedly** [comment]
Does it work on your environment?
`params` refers to `params`, so reference loop happens.

**Comment by wd** [comment]
Haven't noticed before... but it's worked..

**Comment by repeatedly** [comment]
Hmm... In your implementation, `content` value is `params` so it is a Hash object: https://github.com/fluent/fluentd/blob/1a95bde27cd7bae918ac03f3f45fc6542da8a72c/lib/fluent/plugin/in_http.rb#L196
But `Parser#parse` requires given argument is String object, so your patch seems to always raise an exeception: https://github.com/fluent/fluentd/blob/1a95bde27cd7bae918ac03f3f45fc6542da8a72c/lib/fluent/plugin/in_http.rb#L197
What the format do you use in your `in_http` configuration?

**Comment by wd** [comment]
Oh, I use a custom parser... this commit seems buggy, I forget to test use default parser. Close, and will do more test.

**Comment by repeatedly** [comment]
> I use a custom parser

Ah, I see. Okay, I wait new PR.

**Pull request closed without merging**
