### PR TITLE
Fix ThreadError occuring on Signal.trap SIGHUP

### PR DESCRIPTION
**Pull request by sonots**
Fix https://github.com/fluent/fluentd/issues/540

This is the first easiest implementation to fix the issue.

### CODE REVIEW

**Comment by repeatedly** [comment]
If works on @jperville environment, I will merge it.

These code are replaced with ServerEngine's in v0.14.

**Comment by jperville** [comment]
I have applied the patch by hand (wrapping the reloading code in a Thread) and it seems to be working.

Here is the fluentd output after applying the fix:

```
2015-01-19 07:59:37 +0000 [info]: restarting
2015-01-19 07:59:37 +0000 [info]: reading config file path="/etc/fluentd/fluentd.conf"
2015-01-19 07:59:38 +0000 [info]: shutting down fluentd
2015-01-19 07:59:38 +0000 [info]: process finished code=0
2015-01-19 07:59:38 +0000 [error]: fluentd main process died unexpectedly. restarting.
2015-01-19 07:59:38 +0000 [info]: starting fluentd-0.12.3
2015-01-19 07:59:38 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2015-01-19 07:59:38 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '0.7.0'
2015-01-19 07:59:38 +0000 [info]: gem 'fluent-plugin-exclude-filter' version '0.0.1'
2015-01-19 07:59:38 +0000 [info]: gem 'fluent-plugin-record-modifier' version '0.2.0'
2015-01-19 07:59:38 +0000 [info]: gem 'fluentd' version '0.12.3'
2015-01-19 07:59:38 +0000 [info]: gem 'fluentd' version '0.10.58'
2015-01-19 07:59:38 +0000 [info]: using configuration file: <ROOT>
  <match docker.filtered.**>
    type elasticsearch
    host localhost
    port 9999
    index_name fluentd
    type_name fluentd
    logstash_format true
  </match>
</ROOT>
2015-01-19 07:59:38 +0000 [info]: adding match pattern="docker.filtered.**" type="elasticsearch"
```

The `fluentd main process died unexpectedly. restarting` message is logged as expected.

I have also tried spamming `sv hup restart` to see how the program behaves when the HUP signal is received while the reloading code is still working, and it seems to behave sanely.

**Comment by repeatedly** [comment]
@jperville Thanks for the confirmation!

@sonots Is this no problem on regular environment? If so, please merge this patch!

**Comment by sonots** [comment]
It seems sending multiple HUP invokes bad situation with this code. I need SignalThread maybe. Please wait.

**Comment by repeatedly** [comment]
> I need SignalThread

In v0.14, we have a plan to replace supervisor code with ServerEngine.
At that time, we use SignalThread for these signal handling.
So there is no additional patch for this problem.

**Comment by sonots** [comment]
Okay

**Comment by jperville** [comment]
Thank you very much @sonots and @repeatedly . Any chance for a new gem release with the fix?

**Comment by repeatedly** [comment]
I want to include https://github.com/fluent/fluentd/pull/542 for next version.
I will merge https://github.com/fluent/fluentd/pull/542 soon.

**Comment by sonots** [comment]
cherry-picked to v0.10 branch

**Comment by repeatedly** [comment]
@jperville I released v0.12.4. Please try!

**Pull request merged**
