### PR TITLE
Buffered plugins for tests

### PR DESCRIPTION
**Pull request by tagomoris**
Add buffered output plugins to test buffer plugins
 * buffered_stdout: show records in log console w/ buffering
 * buffered_null: show errors only brought by buffer plugins

These plugins are useful to develop 3rd party buffer plugins, so should be included in fluent/plugin/ directory.

And fix in_dummy not to stop to emit records beside any errors of buffer/output plugins to reproduce emit errors continuously.

### CODE REVIEW

**Comment by cosmo0920** [comment]
Is this pull request still active?
If so, I'll try to adopt `Formatter` feature.

**Comment by cosmo0920** [comment]
Using Formatter feature, out_buffered_stdout plugin becomes more simple like this:

```ruby
# 
# License header snipped.
# 
module Fluent
  class BufferedStdoutOutput < BufferedOutput
    Plugin.register_output('buffered_stdout', self)

    config_param :output_type, :default => 'json'

    def configure(conf)
      super
      @formatter = Plugin.new_formatter(@output_type)
      @formatter.configure(conf)
    end

    def write(chunk)
      chunk.msgpack_each do |time, tag, record|
        log.write "#{time} #{tag}: #{@formatter.format(time.localtime.to_s, tag, record)}\n"
      end
      log.flush
    end
  end
end
```

**Comment by tagomoris** [comment]
@cosmo0920 Sorry for late reply, and your points looks correct.
Could you add commits for it and re-create another pull-request? I think it's better to do so.

**Comment by cosmo0920** [comment]
OK. I'll send another PR.

**Comment by tagomoris** [comment]
#847 is now going on.

**Pull request closed without merging**
