### PR TITLE
Fix in_tail input messages loss when receive_lines fail

### PR DESCRIPTION
**Pull request by zheolong**
Fix https://github.com/fluent/fluentd/issues/699

### CODE REVIEW

**Comment by repeatedly** [comment]
Thanks for the patch!
I will check it later.

**Comment by repeatedly** [comment]
This problem should be fixed by https://github.com/fluent/fluentd/issues/567
But this patch seems acceptable. I will test it.

BTW, test code is needed.

**Comment by zheolong** [comment]
@repeatedly Ok, I will check the code and add test for it.

**Comment by repeatedly** [comment]
Hmm writing test seems difficult.
I will try it.

**Comment by repeatedly** [comment]
This will be included in next v0.12.20.

**Comment by repeatedly** [comment]
I will try to write this test.

**Comment by repeatedly** [comment]
@zheolong Update your patch on #810. Could you check it?

**Comment by repeatedly** [comment]
#810 includes this patch.

**Pull request closed without merging**
