### PR TITLE
Add support for drop_oldest_chunk when buffer queue is full

### PR DESCRIPTION
**Pull request by varunkumta**
- Drop oldest chunk from queue without writing to output when buffer
queue is full
- Add test

### CODE REVIEW

**Comment by repeatedly** [comment]
I will check it later.
Supporting `drop_oldest_chunk` itself is no problem for me.

**Comment by repeatedly** [comment]
@varunkumta Could you write your use case?

**Comment by agup006** [comment]
Hi @repeatedly, Use case is for when output plugin relies on time sensitive data and cannot be reached. E.g. connection on FluentD node is blocked or if service is down - continue to rotate data and switch newest data in for oldest data.

**Comment by varunkumta** [comment]
@repeatedly , @agup006 and I work on the Linux omsagent (https://github.com/Microsoft/Build-OMS-Agent-for-Linux) - and the use case he mentioned is one we are adding for handling network outages better, since the data we collect like perf counters is more useful the more recent it is. So we drop older data in favor of newer data.

**Comment by repeatedly** [comment]
@varunkumta @agup006 I understood the situation and I don't have a counter opinion.

@sonots @tagomoris If there is no concern, I will merge this patch.

**Comment by tagomoris** [comment]
LGTM.

**Pull request merged**
