### PR TITLE
v1.13.1

### PR DESCRIPTION
**Pull request by kenhys**
**Which issue(s) this PR fixes**: 

Fixes N/A

**What this PR does / why we need it**: 

Changelog for v1.13.1 (still work in progress)

**Docs Changes**:

N/A

**Release Note**: 

N/A

### CODE REVIEW

**Comment by kenhys** [comment]
Added: https://github.com/fluent/fluentd/pull/3418

**Comment by kenhys** [comment]
Added #3427

**Comment by cosmo0920** [comment]
:+1:

**Comment by kenhys** [comment]
Hmm, there is cases that some test stucks but it should be fixed later.

**Comment by kenhys** [comment]
Oh, It should not merge commit...

**Comment by kenhys** [comment]
v1.13.1 has been pushed.

**Pull request merged**
