### PR TITLE
Use BasicObject for cleanroom

### PR DESCRIPTION
**Pull request by okkez**
BasicObject has following methods:

    >> BasicObject.instance_methods
    => [:!, :==, :!=, :__send__, :equal?, :instance_eval, :instance_exec, :__id__]

### CODE REVIEW

**Comment by okkez** [comment]
BasicObject has been added since Ruby 1.9.

**Comment by repeatedly** [comment]
Thanks

**Comment by okkez** [comment]
I'm not sure about that. I've created new issue on bugs.ruby-lang.org.
https://bugs.ruby-lang.org/issues/13204

**Comment by okkez** [comment]
nobu said:
> Top level constants are constants defined in Object, but BasicObject does not inherit Object.

**Comment by repeatedly** [comment]
Hmm... could you revert it?

**Comment by repeatedly** [comment]
ah, wait. easy to revert via web. I will do it.

**Pull request merged**
