### PR TITLE
Fix logger on Fluent::StringUtil to use $log.

### PR DESCRIPTION
**Pull request by okkez**
backport #907

### CODE REVIEW

**Comment by repeatedly** [comment]
Test failed due to scrub not found...

**Comment by okkez** [comment]
Hmm... fluentd uses string-scrub gem.
I will try to fix this issue later.

**Comment by okkez** [comment]
#933 fixes string-scrub problem.
I've rebased and force pushed.

**Comment by okkez** [comment]
This PR may need #937

**Pull request merged**
