### PR TITLE
ci: add drone.io for arm64 verification

### PR DESCRIPTION
**Pull request by lubinsz**
Signed-off-by: Bin Lu <bin.lu@arm.com>

**Which issue(s) this PR fixes**: 
None

**What this PR does / why we need it**: 
We want to enable arm ci for CNCF projects one by one.

**Docs Changes**:
README.md

**Release Note**: 
None

### CODE REVIEW

**Comment by lubinsz** [comment]
Hi, 
to enable the arm ci with Drone.io needs to be allowed to access repo just as travis does.
An example could be found here:
https://cloud.drone.io/lubinsz/fluentd
I think, we should also active the repo in drone.io, such as https://cloud.drone.io/fluent/fluentd
Thanks.

**Comment by lubinsz** [comment]
@repeatedly 
Any comments?

**Comment by repeatedly** [comment]
Looks good. So we need to create fluent account on drone.io, right?

**Comment by lubinsz** [comment]
> Looks good. So we need to create fluent account on drone.io, right?

Yes.

**Comment by repeatedly** [comment]
Just activated repository: https://cloud.drone.io/fluent/fluentd

**Pull request merged**
