### PR TITLE
Add skip_invalid_event parameter to in_forward. fixes #774

### LINKED ISSUE #774: Add check and skip event option in in_forward
```
App - 1 -> fluentd-a - 2 -> fluentd-b
```

In the above topology, `2` transfer should be safe but `1` sometimes has a problem, e.g. client send an invalid event or something.
For debugging and stability, adding check and skip invalid event option is better.
This is helpful for identifying where is the cause of invalid event, 1 or 2? 

If set `skip_invalid_event true` in in_forward, in_forward checks received event like below.

```
if tag.is_a?(String)
if time.is_a?(Integer)
if record.is_a?(Hash)
```

If detect invalid event, in_forward logs information and skip its event.
This feature also prevents broken records are stored into buffer with PackedForward.

Enable this option on aggreagator may be hard because aggregator receives lots of events from lots of servers.
On the other hard, enable it on forwarder side is reasonable.

### PR DESCRIPTION
**Pull request by repeatedly**
See #774

### CODE REVIEW

**Comment by repeatedly** [comment]
@sonots @tagomoris 
I will add tests but how about this?

**Comment by frsyuki** [comment]
I commented on #774.

**Comment by repeatedly** [comment]
Add tests

**Comment by repeatedly** [comment]
Can I merge this?
After merge this PR, I will release v0.12.20.

**Comment by repeatedly** [comment]
@frsyuki @tagomoris @sonots if no problem, I will merge this today.

**Pull request merged**
