### PR TITLE
Fix: code quality issues

### PR DESCRIPTION
**Pull request by withshubh**
#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes

- Prefer rescuing `StandardError` over `Exception`
- Replace `and`/`or` with `&&`/`||`
- Fixes ambiguous operators in method arguments
- Remove ambiguous regular expression literals in method invocations
- Remove redundant and unnecessary require statement

### CODE REVIEW

**Comment by ashie** [comment]
> * Prefer rescuing StandardError over Exception

I think it should be a separated PR because it may change the behavior.

**Comment by withshubh** [comment]
> > * Prefer rescuing StandardError over Exception
> 
> I think it should be a separated PR because it may change the behavior.

Shall I revert this fix and submit a new PR for the same?

**Comment by ashie** [comment]
> > > * Prefer rescuing StandardError over Exception
> > 
> > 
> > I think it should be a separated PR because it may change the behavior.
> 
> Shall I revert this fix and submit a new PR for the same?

Please remove this commit and force push.
I'll never accept this change because it may break availability.
For example it can't rescue [`SyntaxError`](https://docs.ruby-lang.org/ja/latest/class/SyntaxError.html).

**Comment by withshubh** [comment]
> > > > * Prefer rescuing StandardError over Exception
> > > 
> > > 
> > > I think it should be a separated PR because it may change the behavior.
> > 
> > 
> > Shall I revert this fix and submit a new PR for the same?
> 
> Please remove this commit and force push.
> I'll never accept this change because it may break availability.
> For example it can't rescue [`SyntaxError`](https://docs.ruby-lang.org/ja/latest/class/SyntaxError.html).

Reverted :sparkles: @ashie

**Comment by ashie** [comment]
Thanks! Other changes seems reasonable, I'll merge it.

**Review by cosmo0920 — APPROVED** [review]

**Review by ashie — APPROVED** [review]

**Comment by withshubh** [comment]
Hi @ashie  :wave: 
I ran [DeepSource](https://deepsource.io/) analysis on my fork of this repository to detect these issues. Have a look at the issues caught in this repository by DeepSource [here](https://deepsource.io/gh/withshubh/fluentd/issues/?category=recommended).

DeepSource is a code review automation tool that detects code quality issues and helps you to automatically fix some of them. You can use DeepSource to track test coverage, Detect problems in Dockerfiles, etc. in addition to detecting issues in code.

Can I submit a new PR with the configuration file which I used to configure the analysis?
You can merge the configuration file to continuously analyze the repo and fix code quality issues.

**Comment by ashie** [comment]
Interesting. PR is welcome :smile:

**Pull request merged**
