### PR TITLE
GitHub Actions: Fix a typo

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
none

**What this PR does / why we need it**: 
.github/workflows/build.yaml includes a typo so that CI doesn't work.

**Docs Changes**:
none

**Release Note**: 
none

### CODE REVIEW

**Comment by ashie** [comment]
Hmm, one more failure test is appeared in TLS related tests:

```
2021-02-18T01:09:13.2360942Z Failure: test: can specify multiple TLS versions by min_version/max_version(ServerPluginHelperTest::#server_create_tls::TLS version connection check):
2021-02-18T01:09:13.2362181Z   Exception raised:
2021-02-18T01:09:13.2363101Z   OpenSSL::SSL::SSLError(<SSL_connect returned=1 errno=0 state=error: no protocols available>)
2021-02-18T01:09:13.2364919Z   /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:874:in `connect'
2021-02-18T01:09:13.2366397Z   /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:874:in `open_tls_session'
2021-02-18T01:09:13.2369276Z   /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1516:in `block (5 levels) in <class:ServerPluginHelperTest>'
2021-02-18T01:09:13.2379175Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/assertions.rb:627:in `block in assert_nothing_raised'
2021-02-18T01:09:13.2380656Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/assertions.rb:1633:in `_wrap_assertion'
2021-02-18T01:09:13.2382108Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/assertions.rb:618:in `assert_nothing_raised'
2021-02-18T01:09:13.2383604Z   /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1515:in `block (4 levels) in <class:ServerPluginHelperTest>'
2021-02-18T01:09:13.2385446Z   /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1514:in `each'
2021-02-18T01:09:13.2386807Z   /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1514:in `block (3 levels) in <class:ServerPluginHelperTest>'
2021-02-18T01:09:13.2388290Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:832:in `run_test'
2021-02-18T01:09:13.2389886Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:530:in `block (2 levels) in run'
2021-02-18T01:09:13.2391423Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
2021-02-18T01:09:13.2392904Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
2021-02-18T01:09:13.2394395Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
2021-02-18T01:09:13.2395871Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
2021-02-18T01:09:13.2397520Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
2021-02-18T01:09:13.2398925Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:251:in `run_fixture'
2021-02-18T01:09:13.2400259Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:286:in `run_setup'
2021-02-18T01:09:13.2401571Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:528:in `block in run'
2021-02-18T01:09:13.2402904Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:527:in `catch'
2021-02-18T01:09:13.2404194Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:527:in `run'
2021-02-18T01:09:13.2405517Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
2021-02-18T01:09:13.2406827Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
2021-02-18T01:09:13.2408162Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
2021-02-18T01:09:13.2430918Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
2021-02-18T01:09:13.2434954Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
2021-02-18T01:09:13.2448435Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
2021-02-18T01:09:13.2455178Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
2021-02-18T01:09:13.2456529Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
2021-02-18T01:09:13.2457974Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
2021-02-18T01:09:13.2459559Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
2021-02-18T01:09:13.2461166Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
2021-02-18T01:09:13.2462726Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
2021-02-18T01:09:13.2464269Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
2021-02-18T01:09:13.2465775Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
2021-02-18T01:09:13.2467398Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
2021-02-18T01:09:13.2468834Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunner.rb:25:in `start'
2021-02-18T01:09:13.2470728Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
2021-02-18T01:09:13.2472325Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:446:in `block in run'
2021-02-18T01:09:13.2473754Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:502:in `change_work_directory'
2021-02-18T01:09:13.2475130Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:445:in `run'
2021-02-18T01:09:13.2476661Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:66:in `run'
2021-02-18T01:09:13.2478031Z   /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/test-unit-3.4.0/lib/test/unit.rb:518:in `block (2 levels) in <top (required)>'
2021-02-18T01:09:13.2479586Z /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1515:in `block (4 levels) in <class:ServerPluginHelperTest>'
2021-02-18T01:09:13.2480420Z      1512:           end
2021-02-18T01:09:13.2480756Z      1513:         }
2021-02-18T01:09:13.2481333Z      1514:         [:'TLS1_1', :'TLS1_2'].each { |ver|
2021-02-18T01:09:13.2481799Z   => 1515:           assert_nothing_raised {
2021-02-18T01:09:13.2482655Z      1516:             open_tls_session('127.0.0.1', PORT, cert_path: @cert_path, version: ver) do |sock|
2021-02-18T01:09:13.2483202Z      1517:             end
2021-02-18T01:09:13.2483544Z      1518:           }
```

**Comment by ashie** [comment]
In addition, we should add Ruby 3.0 to matrix.

**Comment by repeatedly** [comment]
I see. Just merged for fixing typo.

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
