### PR TITLE
Fix a bug not to overwrite default value with nil

### PR DESCRIPTION
**Pull request by tagomoris**

### CODE REVIEW

**Comment by tagomoris** [comment]
@repeatedly could you check this?

**Comment by repeatedly** [comment]
Test failed.
Is this change the cause?

**Comment by tagomoris** [comment]
Originally, it's a wrong manner code... I added a commit to fix that.

**Comment by tagomoris** [comment]
Can I merge this?

**Comment by repeatedly** [comment]
LGTM

**Pull request merged**
