### PR TITLE
add filter_stdout

### PR DESCRIPTION
**Pull request by sonots**
This implementation is almost same with the implementation at https://github.com/fluent/fluentd/pull/307#issuecomment-68285384, but filter plugin not output plugin.

### CODE REVIEW

**Comment by sonots** [comment]
I'm going to merge if there is not objection.

**Comment by repeatedly** [comment]
It seems useful. No need copy and stdout trick :+1:

**Comment by sonots** [comment]
Merged!

**Comment by repeatedly** [comment]
Great!

**Pull request merged**
