### PR TITLE
Support pattern start with character classes

### PR DESCRIPTION
**Pull request by okkez**
In prevous version, following pattern raises syntax error:

    <filter>
      @type grep
      <regexp>
        key price
        pattern [1-9]\d*
      </regexp>
    </filter>

This example is derrived from [filter-grep](https://docs.fluentd.org/v1.0/articles/filter_grep#<regexp>-directive)

### CODE REVIEW

**Comment by okkez** [comment]
On the other hand, we want to use regular expression in configuration file sometimes.
So, should we support `config_param :pattern, :regexp` ?

**Comment by repeatedly** [comment]
all tests failed.

**Comment by okkez** [comment]
Sorry, my fault...

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
