### PR TITLE
Disable sigdump after stop

### LINKED ISSUE #3932: Provide option to ignore SIGCONT
### Is your feature request related to a problem? Please describe.

When running under systemd, fluentd will produce a sigdump file even when a normal exit occurs.

Systemd sends a SIGCONT tot he process after the SIGTERM, which causes the sigdump file to be generated, putting unnecessary files in /tmp

### Describe the solution you'd like

An option in the fluentd config file to disable producing sigdump files

### Describe alternatives you've considered

We have adjusted settings for our systemd unit file, but systemd always sends the sigcont.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by abetomo**
**Which issue(s) this PR fixes**: 
Fixes #3932

**What this PR does / why we need it**: 
Don't generate sigdump files after stopping.
https://github.com/fluent/fluentd/pull/4034#issuecomment-1415431569

**Docs Changes**:

**Release Note**:

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1

**Review by ashie — APPROVED** [review]
LGTM

**Review by daipom — APPROVED** [review]
LGTM. Thanks for the fix!

I have checked that Fluentd as a Windows Service can dump correctly by `$ fluent-ctl dump`.

What about `Docs Changes` and `Release Note`?

`Docs Changes` is the fix of https://github.com/fluent/fluentd-docs-gitbook corresponding to this fix.
I think we don't need it this time.

`Release Note` is used for https://github.com/fluent/fluentd/blob/master/CHANGELOG.md.
This is often the same as the title of the PR, but I think it is worth considering a little more this time.

**Comment by ashie** [comment]
Merged. Thanks!

> Docs Changes is the fix of https://github.com/fluent/fluentd-docs-gitbook corresponding to this fix.
> I think we don't need it this time.

I also think it's not needed for this.

**Comment by abetomo** [comment]
> Release Note:

How about "Change to not generate a sigdump file after receiving a SIGTERM signal on non-Windows".

**Comment by daipom** [comment]
> > Release Note:
> 
> How about "Change to not generate a sigdump file after receiving a SIGTERM signal on non-Windows"?

Great!

**Pull request merged**
