### PR TITLE
Support compression in forward transfer

### PR DESCRIPTION
**Pull request by repeatedly**
Experimental implementation.

Adding `compress true` in out_forward configuration.

### CODE REVIEW

**Comment by dhiltonp** [comment]
Can we get feedback on this PR? Is it going to be merged? Is there a reason for it to *not* be merged? Is there something that needs to be fixed in this code before it is accepted?

Thanks!

**Comment by repeatedly** [comment]
We need feedback on several enviroment for checking performance and compression ratio with actual logs.
I post it on #504 but there is no feedback so I'm pending the merge.

**Comment by repeatedly** [comment]
BTW, now this branch conflicts with master.
I will update the patch later.

**Comment by repeatedly** [comment]
rebased for testing.

**Comment by tagomoris** [comment]
At least, this change doesn't include tests.

**Comment by repeatedly** [comment]
Yes because we need test with production traffic.
If this change is useful, I will add tests.

**Comment by Manikantan22** [comment]
Do we still have "compress true" for out_forward plugin?

I am using td-agent2 and tried to use compress true but getting below error in logs.

[warn]: parameter 'compress' in <match pattern> is not used.

**Comment by repeatedly** [comment]
compress doesn't support yet in the upstream.

**Comment by tagomoris** [comment]
This feature will be supported with compressed buffer. Pending.

**Comment by repeatedly** [comment]
https://github.com/fluent/fluentd/pull/1179 is more better way. I close this PR.

**Pull request closed without merging**
