### PR TITLE
Emit less logs

### PR DESCRIPTION
**Pull request by patrobinson**
In an attempt to tackle the issues in #2067 this PR reduces the number of errors and warnings printed out when the output buffer becomes full and raises an exception.

### CODE REVIEW

**Comment by patrobinson** [comment]
pingj @repeatedly

**Comment by ganmacs** [comment]
Such an error log is pretty important for all developers to identify the error reason.
Why do you consider these changes to be needed?

**Comment by patrobinson** [comment]
@ganmacs see the issue described in #2067 
Effectively during a downstream outage these error messages reduce the maximum throughput 10 fold and results in a cascading failure where the buffer is always full of error messages and is never able to recover

**Comment by ganmacs** [comment]
Yes. but this cannot be the reason to remove error logs.
If they aren't necessary,  I'll approve of this change. but they look necessary.

The expected behavior you mentioned in #2067 seems the correct solution to tackle this issue.

**Comment by patrobinson** [comment]
@ganmacs That's fair. I'm happy to close that in favour of that solution, but I don't have the ability to work on it right now

**Pull request closed without merging**
