### PR TITLE
Rename v14 parameters

### PR DESCRIPTION
**Pull request by tagomoris**
I got reviewed for parameters newly added or renamed, and applied changes to rename better names.
This change will be included in v0.14.0 RC2.

### CODE REVIEW

**Comment by repeatedly** [comment]
In this PR, adding several plugins like BufferedNullOutput are intended?

**Comment by tagomoris** [comment]
This change is based on #972, and changes of plugins are done in it.

**Comment by repeatedly** [comment]
Okay, I understood.

**Comment by tagomoris** [comment]
Tests with ruby 2.2.4 on osx is cancelled by Travis trouble, but others are green.

**Pull request merged**
