### PR TITLE
WIP: Refine CI

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
N/A
See also: https://github.com/fluent/fluentd/pull/4375#issuecomment-1886109420

**What this PR does / why we need it**: 

Refine CI settings:

* Unify CI settings for each platforms to one file
* Don't run CI for Ruby head on each `push`/`pull_request` event
  * Because Ruby head is continually changed and not released yet, running CI one shot isn't so meaningful.
  * Instead run it regularly on every Sunday.
* Add `TESTOPT=-v` to all platfroms
  * It's useful to investigate when a test is stalled.
* Remove a hack for Ruby 3.0 on Windows
  * It seems no longer needed.

**Docs Changes**:
N/A

**Release Note**: 
N/A

### CODE REVIEW

**Review by kenhys — APPROVED** [review]
LGTM.

**Comment by ashie** [comment]
Oops, I forgot to remove `WIP` from the title...

**Comment by daipom** [comment]
> Oops, I forgot to remove `WIP` from the title...

Can I remove `WIP` from the title? Is there any reason you haven't removed it yet?

**Comment by daipom** [comment]
Thanks!

**Pull request merged**
