### PR TITLE
Add skip_network_error_at_init option to forward output. fix #731

### LINKED ISSUE #731: Fluentd does not honor dns cache expiration when hostname is initially unresolvable
Fluentd has an option expire_dns_cache. When the hostname of the Fluentd server is unresolvable, I would expect Fluentd to retry later. Instead, the whole process stops with an exception. This is undesirable.

### PR DESCRIPTION
**Pull request by repeatedly**
This option is available when `heartbeat_type` is `tcp` for now.

### CODE REVIEW

**Comment by repeatedly** [comment]
Do we need to support udp heartbeat?

**Comment by harmw** [comment]
I would say this feature should be protocol-agnostic, thus yes UDP should be supported, though you could just merge it now with a disclaimer of some sorts and only support TCP :smile:

To my understanding, the heartbeat is used to ping/check a backend or forwarder, whereas this PR is about mere DNS resolving.

**Comment by mgcrea** [comment]
:+1: this is really needed!

**Comment by tagomoris** [comment]
I think UDP should be supported too.
Any progress?

**Comment by repeatedly** [comment]
We can support UDP but it makes code complicated, e.g. lazy initialization for socket and Heartbeater.
It needs re-writing socket handling of out_forward.
So I want to delay UDP support after other important changes are merged.

**Comment by tagomoris** [comment]
I will come back to this issue after implementing forward plugins with socket/server plugin helpers and v0.14 APIs.

**Comment by tagomoris** [comment]
I created #1399 based on v0.14 code base.

**Pull request closed without merging**
