### PR TITLE
buffer: warning message for restoring buffer with flush_at_shutdown

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
Partial fix for #3970

**What this PR does / why we need it**: 
When `flush_at_shutdown` is `true`, the remaining chunk files during resuming are possibly broken since there may be a power failure or similar failure.

Without this log, even if we notice that we have received corrupted data on the destination server, we can not know which chunks may have been corrupted.

**Docs Changes**:
Not needed.

**Release Note**: 
Add warning messages for restoring buffer with `flush_at_shutdown true`.

### CODE REVIEW

**Review by ashie — APPROVED** [review]
LGTM

Is it O.K. to merge this before #4025 ?

**Comment by daipom** [comment]
Thanks for your review!

Yes, please!

**Review by ashie — CHANGES_REQUESTED** [review]
Sorry, one more thing.

> When flush_at_shutdown is true, the remaining chunk files during resuming are possibly broken since there may be a power failure or similar failure.

Could you add this information as the commit message or comment in the code?

**Comment by daipom** [comment]
Indeed! I will add the comment to the code.

**Comment by daipom** [comment]
I have added the comment at 0807567b538f39db5a6e9be9e87b94f9c269f6e0.

**Review by ashie — APPROVED** [review]
Thanks!

**Comment by daipom** [comment]
Thanks for merging!

**Pull request merged**
