### PR TITLE
Fix ack handling

### PR DESCRIPTION
**Pull request by repeatedly**

### CODE REVIEW

**Comment by repeatedly** [comment]
@mururu Could you check this patch?

**Comment by mururu** [comment]
#1484 is about failure of heartbeat, but ecbdf8d027960af3fd73bb3ceba41c43edcc0181 is a fix for socket leak. So the commit message seems wrong. Except for that, LGTM.

**Comment by repeatedly** [comment]
Yeah, because tcp heartbeat is hung by socket leak. commit message shows it.

**Comment by mururu** [comment]
> because tcp heartbeat is hung by socket leak

I see. It looks perfect.

**Pull request merged**
