### PR TITLE
just tiny typo (grammar)

### PR DESCRIPTION
**Pull request by Hearen**
Signed-off-by: Hearen <LHearen@gmail.com>

**Which issue(s) this PR fixes**: 
Fixes # just tiny typo (grammar)

**What this PR does / why we need it**: 

**Docs Changes**: no

**Release Note**: no

### CODE REVIEW

**Comment by Hearen** [comment]
@cosmo0920 Sorry for the inconvenience, just signed.

**Comment by repeatedly** [comment]
Please fix tests. `test_filter_parser.rb` checks error message.

In addition, don't open new PR for commit fix. Use `git commit -f` for in-place commit update.
Lots of same PR are messy for repository search.

**Comment by Hearen** [comment]
@repeatedly Good morning ;)

Wow, this is becoming ugly now...why such a simple fix could take so much!? Confused now, is there any guides as to exact steps for this? 

At least we should have a *CONTRIBUTING.MD*, I suppose.

**Comment by Hearen** [comment]
@repeatedly It seems it's still not passing the tests after updating the `test_filter_parser.rb`, is there anything I missed out? Sorry to ask this but I got confused now.

**Comment by repeatedly** [comment]
This will be merged when release v1.5.0. Error message change is not trivial fix for users.

**Comment by repeatedly** [comment]
Next release is 1.5.0 so merged.

**Pull request merged**
