### PR TITLE
Don't use popular name to prevent field overwrite when enable_ruby is true

### PR DESCRIPTION
**Pull request by repeatedly**
@sonots please check this patch.

### CODE REVIEW

**Comment by sonots** [comment]
Ah, so local variables are still available even we do `instance_eval { binding }`. 
Is there no way to off local variable scope?

**Comment by sonots** [comment]
It looks better to add some random hex like `6c8047b87c44f301eeae6e522a42d059` than adding `_`.

**Comment by repeatedly** [comment]
I asked @nurse and he said there is no good way for now.
We will consider to add pre-eval based formatter so this patch is enough for temporary solution.

**Comment by repeatedly** [comment]
@sonots if you okay, please merge this.

**Comment by sonots** [comment]
Hmm, no good, but okay to merge...

**Pull request merged**
