### PR TITLE
Use server helper in in_http

### PR DESCRIPTION
**Pull request by ganmacs**
**Which issue(s) this PR fixes**: 

~~I couldn't find any issue about HTTPS support of in_http.~~
#2124

**What this PR does / why we need it**: 

I replaced an implementation of in_http with server helper to prepare for HTTPS support.

**Docs Changes**:

no

**Release Note**: 
no

### CODE REVIEW

**Comment by cosmo0920** [comment]
https://github.com/fluent/fluentd/issues/2124 is related issue.

**Comment by repeatedly** [comment]
I tested this patch and I got lock releated error.

```
2019-05-10 11:39:30.000000000 +0900 test.http: {"k":"hello","k1":1234}
2019-05-10 11:39:30 +0900 [warn]: #0 thread exited by unexpected error plugin=Fluent::Plugin::HttpInput title=:event_loop error_class=ThreadError error="deadlock; recursive locking"
2019-05-10 11:39:30 +0900 [error]: #0 unexpected error error_class=ThreadError error="deadlock; recursive locking"
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:789:in `synchronize'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:789:in `close'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:416:in `close'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/in_http.rb:483:in `on_write_complete'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin/in_http.rb:236:in `block in on_server_connect'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:429:in `block in on'
  2019-05-10 11:39:30 +0900 [error]: #0 (eval):9:in `on_write_complete'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:147:in `on_writable'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:754:in `block in on_writable'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:750:in `synchronize'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/server.rb:750:in `on_writable'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/io.rb:190:in `on_writable'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run_once'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cool.io-1.5.3/lib/cool.io/loop.rb:88:in `run'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/event_loop.rb:93:in `block in start'
  2019-05-10 11:39:30 +0900 [error]: #0 /Users/repeatedly/dev/fluentd/fluentd/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2019-05-10 11:39:30 +0900 [error]: #0 unexpected error error_class=ThreadError error="deadlock; recursive locking"
  2019-05-10 11:39:30 +0900 [error]: #0 suppressed same stacktrace
```

- conf

```
<source>
  @type http
  bind 0.0.0.0
  body_size_limit 32m
  <transport tls>
    insecure true
  </transport>
</source>

<match test.**>
  @type stdout
</match>
```

- test client

```
require 'net/http'
require 'net/https'
require 'msgpack'

record = {'msgpack' => {'k' => 'hello', 'k1' => 1234}.to_msgpack}

def post(path, params)
  http = Net::HTTP.new("127.0.0.1", 9880)
  http.use_ssl = true
  http.verify_mode = OpenSSL::SSL::VERIFY_NONE
  req = Net::HTTP::Post.new(path, {})
  req.set_form_data(params)
  http.request(req)
end

res = post("/test.http?time=#{Time.now.to_i}", record)
puts res.body
```

Could you check?

**Comment by ganmacs** [comment]
> Could you check?

Thank you for reviewing it.
In my environment, it would work with this patch(https://github.com/fluent/fluentd/pull/2413).

**Comment by repeatedly** [comment]
I confirmed it works with 2413.

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
