### PR TITLE
CI: Reduce log level on Windows

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
None

**What this PR does / why we need it**: 
For some reason, the log level is Debug only on Windows.
This makes it harder to find failing tests.

**Docs Changes**:
Not needed.

**Release Note**: 
Not needed.

### CODE REVIEW

**Comment by ashie** [comment]
IMHO I want to leave it as is for a while.

On Windows some tests often become unstable due to other test's state although it shouldn't be.
When I investigate them, I often check which tests are executed before failed tests.
In fact I recently noticed a problem which is caused by a past unrelated pull request.

* https://github.com/fluent/fluentd/pull/4090#issuecomment-1465643573
* https://github.com/fluent/fluentd/pull/4096

It might be hard to find if `-v` isn't specified:

**Comment by daipom** [comment]
I see! Thanks for the explanation! 
Now I understand the benefits of this setting.
I close this.

**Comment by ashie** [comment]
BTW for finding failed test I search ` Failure: ` or `  Error: ` (including former & later spaces) with case sensitive.
It makes easy to find failed tests even if `-v` is added or not.

**Comment by daipom** [comment]
Thanks!!
Do you use `View raw logs` and then search the words?

**Comment by ashie** [comment]
I use both Web UI and raw logs.

**Comment by daipom** [comment]
I see! Thanks!

**Pull request closed without merging**
