### PR TITLE
Add ext_monitor gem to improve Monitor class's operations

### PR DESCRIPTION
**Pull request by ganmacs**
**Which issue(s) this PR fixes**: 
Fixes https://github.com/fluent/fluentd/issues/2645

**What this PR does / why we need it**: 

From ruby 2.6.5, Monitor class became slower due to fixing a deadlock bug (https://bugs.ruby-lang.org/issues/15992). 
https://github.com/nurse/ext_monitor/ mitigates performance for ruby 2.6.5 or later and improves it for prior to 2.6.4  by 2x(https://github.com/fluent/fluentd/issues/2645#issuecomment-546817682).

**Docs Changes**:

no need

**Release Note**: 

same as the title

### CODE REVIEW

**Comment by ganmacs** [comment]
I'll merge this after https://github.com/fluent/fluentd/issues/2380

**Comment by repeatedly** [comment]
By introducing ext_monitor in ruby 2.7, how about changing to `if ext_monitor is installed, fluentd uses it`? It reduces the dependencies and fluentd works even if `ext_monitor` has a problem.

**Comment by ganmacs** [comment]
Sorry, I had a mistake about a condition of installing.
Ruby 2.7 is bundled ext_monitor like mitigation code by default so 2.7 is fast enough without ext_monitor.

>  It reduces the dependencies and fluentd works even if ext_monitor has a problem.

Does it mean like below? and removing `gem.add_runtime_dependency("ext_monitor", [">= 0.1.1", "< 0.2"])` from gemspec?


```rb
if Gem::Version.create(RUBY_VERSION) >= Gem::Version.create('2.7.0')
  require 'monitor'
else
  begin
    require 'ext_monitor'
  rescue LoadError => _
    require 'monitor'
  end
end
```

**Comment by repeatedly** [comment]
> Does it mean like below? 

Yes.

**Comment by ganmacs** [comment]
fixed.
https://github.com/fluent/fluentd/pull/2670/commits/4ae541676e6dce64a2caa90bcc62700f62184638

This log always outputs to STDOUT without ext_monitor. it might be noisy. what do you think of that? @repeatedly

**Comment by repeatedly** [comment]
Maybe, such message is not needed.
td-agent and docker images will install `ext_monitor`.
So most users don't have Monitor issue.

Add to instruction to gem install article is enough.

**Comment by ganmacs** [comment]
> Maybe, such message is not needed.

:+1: 

fixed https://github.com/fluent/fluentd/pull/2670/commits/0a772f2a72b3f8141a762f7d70bea9d7742cd50e

**Pull request merged**
