### PR TITLE
Add priority_key/facility_key options to in_syslog

### PR DESCRIPTION
**Pull request by knqyf263**
I want that `priority` and `facility` are in event record.
Currently, I use `fluent-plugin-record-reformer` to extract `priority` and `facility` values from tags.

However, these values have already been parsed in `in_syslog` plugin.
https://github.com/fluent/fluentd/blob/406c2a1dbfe0c2f14618b9251b67bc1e4f637813/lib/fluent/plugin/in_syslog.rb#L172-L173

I think it is useless to use another plugin for extracting `priority` and `facility`.
Then, I added `include_priority/facility` options to in_syslog.

### CODE REVIEW

**Comment by repeatedly** [comment]
in_tcp's `source_hostname_key` approach is better than `include_priority` because someone wants to specify key.

**Comment by knqyf263** [comment]
@repeatedly Thanks for your feedback!
I fixed. How about this?

**Comment by tagomoris** [comment]
LGTM.

**Comment by knqyf263** [comment]
Thanks!
How about a document?
Shoud I send a PR to `fluent/fluentd-docs` ? 0.12 or 0.14 ?

**Comment by repeatedly** [comment]
I will backport this feature to v0.12 so v0.12 is enough.

**Comment by knqyf263** [comment]
OK!
I sent a PR.
https://github.com/fluent/fluentd-docs/pull/249

**Pull request merged**
