### PR TITLE
Show plugin config ancestors

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
For example

```text
$ bundle exec fluentd --show-plugin-config input:tcp
2015-11-20 11:43:57 +0900 [info]: Show config for input:tcp
2015-11-20 11:43:57 +0900 [info]: 
Fluent::Input
 log_level: string: <nil>
Fluent::SocketUtil::BaseInput
 tag: string: <nil>
 format: string: <nil>
 port: integer: <5150>
 bind: string: <"0.0.0.0">
 source_host_key: string: <nil>
 blocking_timeout: time: <0.5>
Fluent::TcpInput
 delimiter: string: <"\n">
```

**Comment by repeatedly** [comment]
In some cases, `Fluent::SocketUtil::BaseInput` like information is not needed because users don't know its implementation detail.
So by default, hiding such implementation is better.

**Comment by okkez** [comment]
I've changed dumped plugin config appearance.

```text
$ bundle exec fluentd --show-plugin-config=input:tcp
2015-11-24 08:38:32 +0900 [info]: Show config for input:tcp
2015-11-24 08:38:32 +0900 [info]: 
log_level: string: <nil>
tag: string: <nil>
format: string: <nil>
port: integer: <5150>
bind: string: <"0.0.0.0">
source_host_key: string: <nil>
blocking_timeout: time: <0.5>
delimiter: string: <"\n">

$ bundle exec fluentd --show-plugin-config=input:tcp -v
2015-11-24 08:38:39 +0900 [info]: fluent/supervisor.rb:212:show_plugin_config: Show config for input:tcp
2015-11-24 08:38:39 +0900 [info]: fluent/supervisor.rb:227:show_plugin_config: 
Fluent::Input
 log_level: string: <nil>
Fluent::SocketUtil::BaseInput
 tag: string: <nil>
 format: string: <nil>
 port: integer: <5150>
 bind: string: <"0.0.0.0">
 source_host_key: string: <nil>
 blocking_timeout: time: <0.5>
Fluent::TcpInput
 delimiter: string: <"\n">
```

**Comment by repeatedly** [comment]
How about `trace` level?
Some users use `debug` level on testing.
`trace` is useful for developers.

**Comment by okkez** [comment]
I think `debug` is enough to hide verbose output because `--show-plugin-config` have no effect while running fluentd.

**Pull request merged**
