### PR TITLE
in_tail: Skip setup failed watcher to avoid resource leak and log bloat. ref #1713

### PR DESCRIPTION
**Pull request by repeatedly**
This is temporal solution and to log the important information.

In addition, introduce `WatcherSetupError` to unify setup error.
If we have other setup failed cause, we should use this error instead of adhoc logging/error.

### CODE REVIEW

**Comment by repeatedly** [comment]
@mururu Could you check this patch?

**Comment by mururu** [comment]
@repeatedly I can't see why in_tail is related to #1713. It doesn't use in_tail. Could you explain it?

**Comment by repeatedly** [comment]
Ah... sorry. The issue number is incorrect.
https://github.com/fluent/fluentd/issues/1696 is correct.
Will change the commit message.

**Comment by mururu** [comment]
I see.

**Pull request merged**
