### PR TITLE
[#772]  Support multiline string in " quoted string

### PR DESCRIPTION
**Pull request by llby**
Support multiline string in " quoted string

### CODE REVIEW

**Comment by repeatedly** [comment]
Thx! I will check it later.

**Comment by llby** [comment]
Wait! Wait!
I got another simple way.
Please wait!

**Comment by llby** [comment]
@repeatedly I got another simple way.

**Comment by repeatedly** [comment]
It seems good.

@tagomoris @sonots Do you have any concern? Tests are passed so it seems no breaking compatibility.

**Comment by sonots** [comment]
LGTM

**Comment by tagomoris** [comment]
LGTM!

**Comment by repeatedly** [comment]
Thx!

**Comment by llby** [comment]
Hyahhooooo!!!
Thanks a lot!!!
Next I'll try to the 「Add include support for Ruby DSL」

**Pull request merged**
