### PR TITLE
Move plugin util modules to compat

### PR DESCRIPTION
**Pull request by cosmo0920**
`plugin/*_util.rb` should be marked as deprecated module.

### CODE REVIEW

**Comment by tagomoris** [comment]
LGTM.

**Comment by tagomoris** [comment]
CI are failing with following error: `NameError: uninitialized constant Fluent::Plugin::SyslogInput::SocketUtil`
@cosmo0920 Could you check it? It's a bit curious that it occurs only on Travis's osx environment, but should be fixed.

**Comment by cosmo0920** [comment]
Hmm..., It's curious.
I cannot this error in my local environment. :'(

**Comment by tagomoris** [comment]
@cosmo0920 I confirmed that this test fails when I just run `test_in_syslog.rb`.
Could you confirm it?
```
bundle exec rake test TEST=test/plugin/test_in_syslog.rb
```

**Comment by cosmo0920** [comment]
I've rebased and fixed errors.

**Comment by cosmo0920** [comment]
I've fixed a conflict.

**Comment by tagomoris** [comment]
Great fix. Thank you!

**Pull request merged**
