### PR TITLE
github: use issue forms for bug report

### PR DESCRIPTION
**Pull request by kenhys**
**Which issue(s) this PR fixes**: 

Fixes #

**What this PR does / why we need it**: 

It is useful to report bug in forms even though it is still in beta.

ref. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Docs Changes**:

N/A

**Release Note**: 

N/A

### CODE REVIEW

**Comment by kenhys** [comment]
It willl be converted into:

image

**Review by cosmo0920 — APPROVED** [review]
Let's go ahead to use this form!

**Comment by cosmo0920** [comment]
@ashie Can we this form style of bug report template?
Note that this feature is still beta. Be careful to merge and follow yaml settings changes for GitHub Issue template.

**Comment by ashie** [comment]
I'm testing it at https://github.com/ashie/fluentd/issues
It seems work fine!

**Pull request merged**
