### PR TITLE
Migrate out_exec_filter to v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
I've tried to migrate `out_exec_filter` to v0.14 API.
Should we provide asynchronous buffered mode in this plugin?

### CODE REVIEW

**Comment by tagomoris** [comment]
I don't think so > async
Because writing data into pipes is atomic operation, and there are no way to confirm whether it succeeded or not.

**Comment by cosmo0920** [comment]
> I don't think so > async
> Because writing data into pipes is atomic operation, and there are no way to confirm whether it succeeded or not.

I see.

**Comment by tagomoris** [comment]
I missed to comment on this change: can you use `child_process` plugin helper for external process?

**Comment by tagomoris** [comment]
Hmm, I found there are some difficult points with `child_process` plugin helper. So I'll add following fixes for it.

**Comment by cosmo0920** [comment]
> some difficult points

I've found that several difficult points for now:

* `child_process` helper does not have a functionality to distribute output into number of N processes
* `child_process` helper does not have a functionality to handle resident processes

**Comment by tagomoris** [comment]
#1297 does what this pull-request did. Let me close this now.

**Pull request closed without merging**
