### PR TITLE
Doc: add Governance document (draft)

### PR DESCRIPTION
**Pull request by edsiper**
The following PR adds a draft for the upcoming Governance model

### CODE REVIEW

**Comment by edsiper** [comment]
@caniszczyk @repeatedly 

would you please review the draft and provide some suggestions ?

> disclaimer: this draft is a stripped down version of the Kubernetes Community Governance doc

**Comment by caniszczyk** [comment]
@edsiper great start, but what is not mentioned is how:

1) committers get added
2) projects get add

take a peak here at some ideas: https://github.com/containernetworking/cni/blob/master/GOVERNANCE.md

**Comment by edsiper** [comment]
@caniszczyk 

the governance terms have been updated, would you please review and send us some feedback ?

**Comment by caniszczyk** [comment]
@edsiper looks good, may want to link to the code of conduct, but good to merge!

**Comment by edsiper** [comment]
Code of conduct section in GOVERNANCE file has been updated.

**Pull request merged**
