### PR TITLE
Add FOSSA Badge

### PR DESCRIPTION
**Pull request by caniszczyk**
CNCF is experimenting with automated license scanning tools.

Signed-off-by: Chris Aniszczyk <caniszczyk@gmail.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
cc: @edsiper

**Comment by repeatedly** [comment]
Is this same with https://github.com/fluent/fluentd/pull/1681 ?

**Comment by edsiper** [comment]
@repeatedly yeah, looks like it's the same.

@caniszczyk did you trigger #1681 ?

**Comment by caniszczyk** [comment]
@edsiper yes it was me :)

**Comment by edsiper** [comment]
merged.

**Pull request merged**
