### PR TITLE
Add ruby 2.7.0

### PR DESCRIPTION
**Pull request by ganmacs**
Signed-off-by: Yuta Iwama <ganmacs@gmail.com>

**Which issue(s) this PR fixes**: 
none

**What this PR does / why we need it**: 

Add ruby 2.7 ci support

**Docs Changes**:

none

**Release Note**: 

none

### CODE REVIEW

**Comment by ganmacs** [comment]
Right. I'll use rake 12 becuase it supports ruby 2.1. but now I'm working on fixing other errors https://travis-ci.org/fluent/fluentd/jobs/629558001?utm_medium=notification&utm_source=github_status.

**Comment by repeatedly** [comment]
We will drop ruby 2.1/2.2/2.3 support after a few more days.
Waiting it is one approach.

**Comment by ganmacs** [comment]
If I couldn't fix the error this year, I'll do so~(I think it's not good to mix adding support and droping support in the same PR).

**Comment by ganmacs** [comment]
Tests are passed. I'll merge later https://travis-ci.org/fluent/fluentd/builds/629889073?utm_medium=notification&utm_source=github_status

**Pull request merged**
