### PR TITLE
Drop testing TLS 1.1

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
none

**What this PR does / why we need it**: 
Recent distributions disables TLS 1.1 by default due to its
vulnerability so that tests for it is always failed:

2021-02-18T01:09:13.2360942Z Failure: test: can specify multiple TLS versions by min_version/max_version(ServerPluginHelperTest::#server_create_tls::TLS version connection check):
2021-02-18T01:09:13.2362181Z   Exception raised:
2021-02-18T01:09:13.2363101Z   OpenSSL::SSL::SSLError(<SSL_connect returned=1 errno=0 state=error: no protocols available>)
...
2021-02-18T01:09:13.2479586Z /home/runner/work/fluentd/fluentd/test/plugin_helper/test_server.rb:1515:in `block (4 levels) in <class:ServerPluginHelperTest>'
2021-02-18T01:09:13.2480420Z      1512:           end
2021-02-18T01:09:13.2480756Z      1513:         }
2021-02-18T01:09:13.2481333Z      1514:         [:'TLS1_1', :'TLS1_2'].each { |ver|
2021-02-18T01:09:13.2481799Z   => 1515:           assert_nothing_raised {
2021-02-18T01:09:13.2482655Z      1516:             open_tls_session('127.0.0.1', PORT, cert_path: @cert_path, version: ver) do |sock|
2021-02-18T01:09:13.2483202Z      1517:             end
2021-02-18T01:09:13.2483544Z      1518:           }

**Docs Changes**:
none

**Release Note**: 
none

### CODE REVIEW

**Comment by ashie** [comment]
Major web browsers also drops TLS1.0/1.1 support.
IPA make them deprecated: https://www.ipa.go.jp/security/ipg/documents/ipa-cryptrec-gl-3001-3.0.1.pdf

**Comment by repeatedly** [comment]
Merged. But ruby 2.5 test has weird behaviour.

**Comment by ashie** [comment]
> Merged. But ruby 2.5 test has weird behavior with timeout.

I'm checking it.

**Comment by ashie** [comment]
> But ruby 2.5 test has weird behavior with timeout.

Probably it's reproduced on my local environment:
```
Traceback (most recent call last):
	38: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit.rb:518:in `block (2 levels) in <top (required)>'
	37: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:66:in `run'
	36: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:445:in `run'
	35: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:502:in `change_work_directory'
	34: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/autorunner.rb:446:in `block in run'
	33: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'
	32: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunner.rb:25:in `start'
	31: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'
	30: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:39:in `run'
	29: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'
	28: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'
	27: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'
	26: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'
	25: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'
	24: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
	23: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
	22: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
	21: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
	20: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:53:in `run'
	19: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testsuite.rb:124:in `run_test'
	18: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:527:in `run'
	17: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:527:in `catch'
	16: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/testcase.rb:528:in `block in run'
	15: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:286:in `run_setup'
	14: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:251:in `run_fixture'
	13: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
	12: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
	11: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:270:in `block in create_fixtures_runner'
	10: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:266:in `block in create_fixtures_runner'
	 9: from /home/aho/Projects/Fluentd/fluentd/vendor/bundle/ruby/2.5.0/gems/test-unit-3.4.0/lib/test/unit/fixture.rb:278:in `run_fixture_callback'
	 8: from /home/aho/Projects/Fluentd/fluentd/test/plugin/test_out_http.rb:132:in `block in <class:HTTPOutputTest>'
	 7: from /home/aho/Projects/Fluentd/fluentd/test/plugin/test_out_http.rb:406:in `http_client'
	 6: from /home/aho/Projects/Fluentd/fluentd/test/plugin/test_out_http.rb:58:in `http_client'
	 5: from /home/aho/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:609:in `start'
	 4: from /home/aho/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
	 3: from /home/aho/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
	 2: from /home/aho/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:981:in `connect'
	 1: from /home/aho/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:45:in `ssl_socket_connect'
/home/aho/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:45:in `wait_readable': Interrupt
```

**Comment by ashie** [comment]
@repeatedly Since it's caused by the combination of older Ruby and WEBrick, it will be resolved by #3257.
In addition, there is a wrong timeout calculation for a test (I've add a commit to fix it to #3257).

**Pull request merged**
