### PR TITLE
Implement RPC server for better instance management

### PR DESCRIPTION
**Pull request by repeatedly**
RPC server is launched when an user sets rpc_endpoint in system directive.
Each handler returns JSON response by default.

In the future, we use pipe between supervisor and workers.

Related to https://github.com/fluent/fluentd/issues/575 issue.

### CODE REVIEW

**Comment by repeatedly** [comment]
This is prototype so some features, e.g. stop sources, are not implemented yet.

**Comment by tagomoris** [comment]
I think that RPC handlers (mounted on webrick) should be separated from `supervisor.rb`.

**Comment by repeatedly** [comment]
@tagomoris What do you mean? Mount handler code should be in rpc/handler.rb or similar?

**Comment by tagomoris** [comment]
@repeatedly yes. `fluent/supervisor.rb` is too big for me now.

**Comment by repeatedly** [comment]
@tagomoris I agree > too big.
How to separate code? Open class? module mixin?
For separating code, need to access internal state of Supervisor.

**Comment by tagomoris** [comment]
How about to do `@rpc_server.supervisor = self` just before `@rpc_server.start`?

**Comment by repeatedly** [comment]
@tagomoris RPC server is not only for supervisor so your approach also seems a bit tricky.
For separating code, we have several approaches in rpc/handlers/supervisor.rb:

```rb
module Fluent::RPC::Supervisor
  def setup_handlers(rpc_server, supervisor)
    # signal handlers are private
    rpc_server.mount_proc { |req, res|
      supervisor.__send__(:xxx)
    }
    # ...
  end
end
```

or

```
module Fluent
  class Supervisor
     # same as current patch
  end
end
```

or

```
module Fluent::RPC::Supervisor
  # include in actual supervisor code.
  module SetupHandlersMixin
     # ... setup code
  end
end
```

Separating code is good but it seems to bring another complexity for me.
Does someone have a good idea?

**Comment by repeatedly** [comment]
Does someone have more feedback?
I want a feedback of RPC endpoints. `/plugins/buffers/flush` should be `/buffers/flush` or another?

**Comment by repeatedly** [comment]
I use `rpc_endpoit` for launching RPC server.
This should be separated into rpc_bind / rpc_port with default values like `rpc_bind` is `localhost` and `rpc_port` is `23224`?

**Comment by repeatedly** [comment]
I have a plan to introduce ServerEngine and it replaces some supervisor code with serverengine's part so
I delayed separating code.

**Comment by repeatedly** [comment]
Another approach is Slack like HTTP RPC Style API: https://api.slack.com/methods

- `/api/plugins.flushBuffers`
- `/api/processes.killWorkers`
- `/api/processes.interruptWorkers`
- `/api/config.reload`

It seems better than REST like API for me.
What do you think?

**Comment by sonots** [comment]
HTTP RPC Style looks nice :)

**Comment by repeatedly** [comment]
No additional comment?
If nothing, I will merge this PR today.

**Comment by tagomoris** [comment]
LGTM

**Comment by repeatedly** [comment]
@sonots You can implement `/api/plugins.stopSources` :)

**Comment by JindongChen** [comment]
Is there any plan to implement /api/plugins.stopSources? I'm looking forward to stop source when output to Elasticsearch is blocking.

**Pull request merged**
