### PR TITLE
Fix plugin load order. Loading built-in plugins should be last

### PR DESCRIPTION
**Pull request by repeatedly**
`Registry` now loads built-in plugins first, but it should be last.
Fluentd should prefer 3rd party plugins to overwrite behaviour and keep to use same plugin, e.g. parser plugin.

### CODE REVIEW

**Comment by repeatedly** [comment]
@tagomoris Check this patch.

**Comment by repeatedly** [comment]
Windows environment tests are toooooo unstable.
I re-run AppVeyor test over 20+ times but tests are still failed...

**Comment by repeatedly** [comment]
@tagomoris ping?

**Comment by repeatedly** [comment]
Which point? fluentd gem is removed from gem search > https://github.com/fluent/fluentd/pull/1410/files#diff-da556f72b0de83b0e659240bf9d879bbR92

**Comment by tagomoris** [comment]
Oh, I missed it.
Looks good to me - Of course, it's better to have some tests.

**Comment by repeatedly** [comment]
yeah, adding test is better but it needs extra gem installation.
It is hard in unit test. This is TODO of fluentd's integration tests.

**Pull request merged**
