### PR TITLE
Add test for Fluent::Log

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by tagomoris** [comment]
@okkez Can you add more tests for PluginLogger and PluginLoggerMixin?
I think it should have dummy plugin instances, and I think we can use `Fluent::Plugin::TestBase` for it.

**Comment by okkez** [comment]
OK, I will try to add tests for PluginLogger and PluginLoggerMixin.

**Comment by okkez** [comment]
@tagomoris I've added tests for PluginLogger and PluginLoggerMixin.

**Comment by tagomoris** [comment]
@okkez Thank you very much!

**Pull request merged**
