### PR TITLE
v1.16: in_tail: Fix warning about overwriting entry with follow_inodes

### PR DESCRIPTION
**Pull request by daipom**
**Which issue(s) this PR fixes**: 
None.

**What this PR does / why we need it**: 
Apply #4214 to v1.16.

**Docs Changes**:
No need.

**Release Note**: 
Same as the title.

### CODE REVIEW

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
:+1:

**Comment by ashie** [comment]
I'm considering to remove current v1.16 branch, since the current master branch (e12069351a431b30bd84996d60ff9c4a7e78adce) isn't still so far from v1.16.
We'll release v1.16.2 from master branch then recreate v1.16 from more recent revision.

**Comment by daipom** [comment]
I agree!

**Comment by ashie** [comment]
I've removed v1.16 branch.

**Pull request merged**
