### PR TITLE
in_tail: Ensure to reach EOF after rotate even if throttling is enabled

### LINKED ISSUE #2478: in_tail take long time to found rotated files
related to issue https://github.com/fluent/fluentd/issues/2477

Will there be any risk if I change read_more = true to read_more = false, such as losing record or other issues, just in my copy of in_tail source code?

We came across a problem here. We have ten log files, our log-generator writes record(0.5KB per record) to them by 1000 lines/s each and rotate it by renaming the file to another name(the inode changed but filename stay the same) if the size of the file reaches 100MB. We use in_tail to collect these files.

We found two problems.

1. when the file is rotated, it takes a long time for in_tail to discover the new inode of the logfile, and after several rotate, it seems in_tail just lost some of the rotated files(rotate is quite fast)
2. when starting the fluentd, I found it takes a long time for in_tail to start_watchers for these files when I look at the log of fluentd(I add some debug log after setup_watcher). And with the rotate issues, it seems fluentd finally lost some of the log files.

I'm not familiar with in_tail's performance, so maybe it's not in_tail's problem but the way I use it. The usage of CPU is not high and the flush speed is ok.

For the moment, I solve these two problems with change read_more = true to read_more = false(it take effects), but I'm not sure if there will be any risk with this change.

It would be very kind of you if you can give me some advice with these two problems.

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
Fixes #2478

**What this PR does / why we need it**: 
Although log throttling feature is landed at #3185 (and #3379), it has still remaining issue mentioned at https://github.com/fluent/fluentd/issues/2478#issuecomment-512086345
When the throttling feature is enabled and rotation is occurred, remaining lines will be discarded.
(When it's not enabled, in_tail make sure to reach EOF with blocking other tasks.)
This patch ensure to reach EOF even if throttling is enabled.

**Docs Changes**:
none

**Release Note**: 
~~Same with  #3185 (if this PR is landed on v1.13)~~
Same with the title

### CODE REVIEW

**Comment by ashie** [comment]
I've added tests for it, it seems work as expected.

**Review by kenhys — APPROVED** [review]
LGTM

**Comment by kenhys** [comment]
@cosmo0920 could you check, please?

**Review by cosmo0920 — APPROVED** [review]
LGTM! :+1:

**Comment by ashie** [comment]
Thanks!

**Comment by cosmo0920** [comment]
:tada:

**Pull request merged**
