### PR TITLE
backport: Fix test for TimeSlicedOutput

### PR DESCRIPTION
**Pull request by okkez**
This backports #916

### CODE REVIEW

**Comment by repeatedly** [comment]
If backport this change to v0.12, do existing TimeSlicedOutput plugin tests become broken?

**Comment by okkez** [comment]
No. We don't need to fix out_exec plugin (existing TimeSlicedOutput plugin) in this PR.
We have fixed out_file plugin, because out_file plugin's test uses BufferedOutputTestDriver.

**Comment by tagomoris** [comment]
If 3rd party time sliced output plugins uses BufferedOutputTestDriver, then it should be broken.

**Comment by tagomoris** [comment]
@repeatedly Don't you think to merge this change?

**Comment by repeatedly** [comment]
@okkez Could you rebase the patch for current v0.12?

**Comment by okkez** [comment]
Rebased.

**Comment by repeatedly** [comment]
Thx!

**Pull request merged**
