### PR TITLE
v1.12.3

### PR DESCRIPTION
**Pull request by ashie**
**Which issue(s) this PR fixes**: 
none

**What this PR does / why we need it**: 
For releasing v1.12.3

**Docs Changes**:
none

**Release Note**: 
none

### CODE REVIEW

**Comment by ashie** [comment]
I'll merge it & releaes v1.12.3 after having a lunch :smile:

**Comment by ashie** [comment]
Some tests are failed, but they are known unstable tests. We'll try to fix them later.

https://github.com/fluent/fluentd/pull/3347/checks?check_run_id=2416159689
(It should be fixed by https://github.com/treasure-data/serverengine/pull/112)

```
2021-04-23T02:55:09.1936837Z Failure: test: cannot create 2 or more servers using same bind address and port if shared option is false[server_create tcp](ServerPluginHelperTest::#server_create and #server_create_connection)
2021-04-23T02:55:09.1952933Z D:/a/fluentd/fluentd/test/plugin_helper/test_server.rb:328:in `block (2 levels) in <class:ServerPluginHelperTest>'
2021-04-23T02:55:09.1954150Z      325:         assert_nothing_raised do
2021-04-23T02:55:09.1954989Z      326:           @d.__send__(m, :myserver, PORT, proto: proto, shared: false, **kwargs){|x| x }
2021-04-23T02:55:09.1955718Z      327:         end
2021-04-23T02:55:09.1956431Z   => 328:         assert_raise(Errno::EADDRINUSE, Errno::EACCES) do
2021-04-23T02:55:09.1957384Z      329:           d2.__send__(m, :myserver, PORT, proto: proto, **kwargs){|x| x }
2021-04-23T02:55:09.1957931Z      330:         end
2021-04-23T02:55:09.1958344Z      331:       ensure
2021-04-23T02:55:09.1958632Z 
2021-04-23T02:55:09.1959360Z <[Errno::EADDRINUSE, Errno::EACCES]> expected but was
2021-04-23T02:55:09.1960865Z <Errno::NOERROR(<No error - bind(2)>)
```


https://github.com/fluent/fluentd/pull/3347/checks?check_run_id=2416159672

```
2021-04-23T02:51:09.5681763Z Error: test: can format/write data correctly(FileOutputTest::fully configured output): Zlib::GzipFile::Error: not in gzip format
2021-04-23T02:51:09.5683096Z D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:317:in `initialize'
2021-04-23T02:51:09.5684369Z D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:317:in `new'
2021-04-23T02:51:09.5685453Z D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:317:in `block (4 levels) in <class:FileOutputTest>'
2021-04-23T02:51:09.5686429Z D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:316:in `open'
2021-04-23T02:51:09.5687374Z D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:316:in `block (3 levels) in <class:FileOutputTest>'
2021-04-23T02:51:09.5689107Z D:/a/fluentd/fluentd/test/plugin/test_out_file.rb:321:in `block (2 levels) in <class:FileOutputTest>'
```

https://cloud.drone.io/fluent/fluentd/1297/1/2

```
Failure: test: flushed chunk will be committed after child process successfully exits(ExecOutputTest::when executed process dies unexpectedly)
/drone/src/test/plugin/test_out_exec.rb:279:in `block (2 levels) in <class:ExecOutputTest>'
     276:       expect_data =
     277:         %[2011-01-02 13:14:15\ttest\tv1\n] +
     278:         %[2011-01-02 13:14:15\ttest\tv2\n]
  => 279:       assert_equal expect_data, data
     280:
     281:       assert{ d.instance.buffer.queue.empty? }
     282:       assert{ d.instance.dequeued_chunks.empty? }
<"2011-01-02 13:14:15\ttest\tv1\n" + "2011-01-02 13:14:15\ttest\tv2\n">(UTF-8) expected but was
<"">(ASCII-8BIT)
```

**Comment by ashie** [comment]
I've pushed it to RubyGems
* https://rubygems.org/gems/fluentd/versions/1.12.3
* https://rubygems.org/gems/fluentd/versions/1.12.3-x64-mingw32
* https://rubygems.org/gems/fluentd/versions/1.12.3-x86-mingw32

**Comment by fujimotos** [comment]
... aaand here is the release blog post:

https://github.com/fluent/fluentd-website/pull/139

**Pull request merged**
